# Shared settings for the pdm test harness. Sourced, not run.
#
# Copyright (c) 2026 Herman van Hazendonk <github.com@herrie.org>
# SPDX-License-Identifier: Apache-2.0

# Where the OE build lives. Override with PDM_BUILD_DIR=... if yours differs.
PDM_BUILD_DIR="${PDM_BUILD_DIR:-/media/herrie/LuneOS/wrynose/webos-ports}"

# This checkout, which is what the harness builds - not the SRCREV the recipe
# pins. Everything runs against your working tree, committed or not.
PDM_SRC_DIR="${PDM_SRC_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

PDM_RECIPE="com.webos.service.pdm"

# One machine per architecture we ship.
#   armv7    mindphone        (no target attached here; build coverage only)
#   aarch64  sargo            (Pixel 3a, reachable over adb)
#   x86-64   qemux86-64       (the LuneOS VirtualBox VMs run this image)
PDM_MACHINE_armv7="${PDM_MACHINE_armv7:-mindphone}"
PDM_MACHINE_aarch64="${PDM_MACHINE_aarch64:-sargo}"
PDM_MACHINE_x86_64="${PDM_MACHINE_x86_64:-qemux86-64}"
PDM_ARCHES="${PDM_ARCHES:-armv7 aarch64 x86_64}"

# ssh into the VirtualBox VM. VBoxManage shows this forward on both LuneOS VMs.
PDM_VBOX_SSH_PORT="${PDM_VBOX_SSH_PORT:-5522}"
PDM_VBOX_SSH_HOST="${PDM_VBOX_SSH_HOST:-root@localhost}"
PDM_VBOX_VM="${PDM_VBOX_VM:-LuneOS-qemux86-64-testing}"

PDM_SSH_OPTS="${PDM_SSH_OPTS:--o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=10}"

pdm_machine_for() {
    case "$1" in
        armv7)   echo "$PDM_MACHINE_armv7" ;;
        aarch64) echo "$PDM_MACHINE_aarch64" ;;
        x86_64|x86-64) echo "$PDM_MACHINE_x86_64" ;;
        *) echo "unknown arch: $1" >&2; return 1 ;;
    esac
}

pdm_die()  { echo "error: $*" >&2; exit 1; }
pdm_info() { echo "==> $*"; }

# A conf fragment handed to bitbake with -R, so the build uses this working
# tree instead of the recipe's SRCREV and nothing in the layer is touched.
pdm_write_externalsrc_conf() {
    local out="$1"
    cat > "$out" <<CONF
# Generated by the pdm test harness - passed to bitbake with -R, never installed.
INHERIT += "externalsrc"
EXTERNALSRC:pn-${PDM_RECIPE} = "${PDM_SRC_DIR}"
EXTERNALSRC_BUILD:pn-${PDM_RECIPE} = "\${WORKDIR}/build"
# externalsrc drops SRC_URI, so the checksums pinned for the git fetch go too.
PV:pn-${PDM_RECIPE} = "1.0.1-local"
CONF
}
